{{- if .Values.postgresql.enabled }}
{{- $full := include "hangar.fullname" . -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $full }}-postgres
  labels: {{- include "hangar.labels" . | nindent 4 }}
spec:
  selector: {{- include "hangar.selector" . | nindent 4 }}
    app.kubernetes.io/component: postgres
  ports: [{name: pg, port: 5432, targetPort: 5432}]
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ $full }}-postgres
  labels: {{- include "hangar.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  serviceName: {{ $full }}-postgres
  replicas: 1
  selector:
    matchLabels: {{- include "hangar.selector" . | nindent 6 }}
      app.kubernetes.io/component: postgres
  template:
    metadata:
      labels: {{- include "hangar.selector" . | nindent 8 }}
        app.kubernetes.io/component: postgres
    spec:
      securityContext: {fsGroup: 999, seccompProfile: {type: RuntimeDefault}}
      containers:
        - name: postgres
          image: {{ .Values.postgresql.image }}
          env:
            - {name: POSTGRES_USER, value: hangar}
            - {name: POSTGRES_DB, value: hangar}
            - {name: PGDATA, value: /var/lib/postgresql/data/pgdata}
            - name: POSTGRES_PASSWORD
              valueFrom: {secretKeyRef: {name: {{ include "hangar.secretName" . }}, key: POSTGRES_PASSWORD}}
          ports: [{containerPort: 5432, name: pg}]
          securityContext: {allowPrivilegeEscalation: false, runAsNonRoot: true, runAsUser: 999, runAsGroup: 999, readOnlyRootFilesystem: true, capabilities: {drop: [ALL]}}
          readinessProbe:
            exec: {command: [pg_isready, -U, hangar, -d, hangar]}
            periodSeconds: 5
          resources: {{- toYaml .Values.postgresql.resources | nindent 12 }}
          volumeMounts:
            - {name: data, mountPath: /var/lib/postgresql/data}
            - {name: run, mountPath: /var/run/postgresql}
            - {name: tmp, mountPath: /tmp}
      volumes:
        - name: run
          emptyDir: {}
        - name: tmp
          emptyDir: {}
  volumeClaimTemplates:
    - metadata: {name: data}
      spec:
        accessModes: [ReadWriteOnce]
        {{- with .Values.postgresql.storageClass }}
        storageClassName: {{ . }}
        {{- end }}
        resources: {requests: {storage: {{ .Values.postgresql.storage }}}}
{{- end }}
